apiVersion: apps/v1
kind: Deployment

metadata:
  name: test-gpu-topology
  labels:
    app: test-gpu-topology
spec:
  replicas: 1

  selector: # define how the deployment finds the pods it mangages
    matchLabels:
      app: test-gpu-topology
  template: # define the pods specifications
    metadata:
      labels:
        app: test-gpu-topology
    spec:
      hostIPC: true
      containers:
      - name: test-gpu-topology
        image: registry.cn-hangzhou.aliyuncs.com/lijj/test-gpu-topology:demo1
        imagePullPolicy: IfNotPresent
        resources:
          limits:
             aliyun.com/gpu: 1
        env:
          - name: NVIDIA_VISIBLE_DEVICES
            value: "0"
          - name: CUDA_MPS_PIPE_DIRECTORY
            value: "/tmp/nvidia-mps"
          - name:  CUDA_MPS_LOG_DIRECTORY
            value:  "/tmp/nvidia-log"
          - name: CUDA_VISIBLE_DEVICES
            value: "0"
          - name: NVIDIA_DRIVER_CAPABILITIES
            value: compute,utility
          - name: CUDA_MPS_ACTIVE_THREAD_PERCENTAGE
            value: "30"
        volumeMounts:
          - name: nvidia-mps
            mountPath: /tmp/nvidia-mps
      volumes:
         - name: nvidia-mps
           hostPath:
             path: /tmp/nvidia-mps